---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

stages:
  - test
  - deploy_demo

env:
  global:
    - secure: RVHmsLzsqUhygKMLEqtioHP6E8Uj6kFegDT2+u1iE2mRIdVPaD2ISZzLO92ZNBs04M3ugHYsfwUyW5yAijD77Vg1fvWQiaeG+HCCJfjFvU3lRq8HervVVrEFp+WK+rw6KesEQkZwIVCxp7JqXZQR05Ju++f7shMvESAqi0vdT1U=
  matrix:
    - SCRIPT=test:all
    - SCRIPT=test:fastboot
    - SCRIPT=test:node

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install --no-lockfile

script: npm run $SCRIPT

deploy:
  provider: npm
  email: info@simplabs.com
  api_key:
    secure: dKp+BvoSv8vUN90m9fH2oOK/sQ12K5B5BrWjfn1m2evpc9TFZGHLlqSsAw4Cq9JmK7SgRKsuh4O2k1CO8QAXW6mMjD/NSGJfBz+grdXE20kqOlIPvj9sQ9PVpqgmTA5bZvhbhXn8ybKqgTabZZrED9eMkrSqMN5xU1oW414DNwQ=
  on:
    tags: true
    repo: simplabs/ember-simple-auth

jobs:
  include:
    - stage: deploy_demo
      script: npm i -g now-pipeline; cd server && now-pipeline-prune && now-pipeline --alias ember-simple-auth-server.now.sh; now-pipeline-prune && now-pipeline --alias ember-simple-auth.now.sh

notifications:
  email: false
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
